layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

subtitle: Principal Software Architect

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  keybase: impressivenerd
  linkedin: jeffreypatyk
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: impressivenerd
  # unsplash: your_username
  # vk: your_username
  website: https://patyk.dev
  youtube: digitalbrink
  dev: impressivenerd

topics:
  - name: Angular
    web_url: https://angular.io/
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/angular/angular.png
    
  - name: Go
    web_url: https://golang.org/
    image_url: https://golang.org/lib/godoc/images/go-logo-blue.svg

  - name: Sass
    web_url: https://github.com/topics/sass
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png
    
  - name: Unity
    web_url: https://unity.com/
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/unity/unity.png
  
  - name: Dart
    web_url: https://dart.dev/
    image_url: https://raw.githubusercontent.com/Impressivenerd/personal-website/master/assets/Dart%20Icon.png

  - name: Kotlin
    web_url: https://kotlinlang.org/
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/kotlin/kotlin.png
 

theme: jekyll-theme-merlot
