layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

subtitle: Principal Software Engineer

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  keybase: impressivenerd
  linkedin: jeffreypatyk
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: impressivenerd
  # unsplash: your_username
  # vk: your_username
  website: https://patyk.dev
  youtube: digitalbrink
  dev: impressivenerd

topics:
  - name: Angular
    web_url: https://angular.io/
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/angular/angular.png
    
  - name: Go
    web_url: https://golang.org/
    image_url: https://golang.org/lib/godoc/images/go-logo-blue.svg

  - name: Sass
    web_url: https://github.com/topics/sass
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png
    
  - name: Unity
    web_url: https://unity.com/
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/unity/unity.png
  
  - name: Dart
    web_url: https://dart.dev/
    image_url: https://raw.githubusercontent.com/Impressivenerd/personal-website/master/assets/Dart%20Icon.png

  - name: Kotlin
    web_url: https://kotlinlang.org/
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/kotlin/kotlin.png

certifications:
  - name: CompTIA A+
    web_url: https://www.youracclaim.com/badges/67e11161-b376-4f99-bb82-14cac2a1ea14/linked_in_profile
    image_url: https://images.youracclaim.com/images/74831957-3dc2-4460-9af2-1bf59e392c47/CompTIA_A_2B.png
    
  - name: CompTIA Network+
    web_url: https://www.youracclaim.com/badges/351a1b9a-dfe9-440e-b6bc-292476baf743/linked_in_profile
    image_url: https://images.youracclaim.com/images/9f3a0aa9-ad62-4687-9b11-ddb626259fe2/CompTIA_Network_2B.png
    
  - name: CompTIA Server+
    web_url: https://www.youracclaim.com/badges/27b1f1b5-ee40-4a52-b59e-b5b1054299de/linked_in_profile
    image_url: https://images.youracclaim.com/images/ea703f5e-fab3-4397-aae9-9ffcc16b6ffc/CompTIA_Server_2B.png

theme: jekyll-theme-merlot
